### PR TITLE
Added content to your contact page

### PR DESCRIPTION
**Pull request by arsenhh-byte**

### CODE REVIEW

**Comment by Knightgamer** [comment]
This works but please fix the home page
The image is too big

**Review by Knightgamer — COMMENTED** [review]
the UI looks good

**Review by Knightgamer — CHANGES_REQUESTED** [review]
Please make the UI better

**Comment by arsenhh-byte** [comment]
Working on it.

**Review by Knightgamer — APPROVED** [review]
About.js page's UI is much more better

**Pull request merged**
